FROM nginx:stable-alpine
COPY --from=build /cloud-com-app/dist/cloud-com-app /usr/share/nginx/html
COPY --from=build /cloud-com-app/.nginx.conf /etc/nginx/sites-enabled/default
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
