version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: angular-build
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: angular-nginx
    ports:
      - "80:80"
    depends_on:
      - app
